// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2PzC-27eHVcexaNAwAuxuETKBgIIN9vU',
    appId: '1:726525059893:web:64f8b031675dbf8064227c',
    messagingSenderId: '726525059893',
    projectId: 'cab-booking-81372',
    authDomain: 'cab-booking-81372.firebaseapp.com',
    databaseURL: 'https://cab-booking-81372-default-rtdb.firebaseio.com',
    storageBucket: 'cab-booking-81372.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQGZxOHSuKDidgy0qRu_tfajCPHtnE630',
    appId: '1:726525059893:android:e1ca6fad87218d1a64227c',
    messagingSenderId: '726525059893',
    projectId: 'cab-booking-81372',
    databaseURL: 'https://cab-booking-81372-default-rtdb.firebaseio.com',
    storageBucket: 'cab-booking-81372.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9iiR4p_LHPTECKNCSZIgtDqsnMMpToz8',
    appId: '1:726525059893:ios:2964c76e7654343f64227c',
    messagingSenderId: '726525059893',
    projectId: 'cab-booking-81372',
    databaseURL: 'https://cab-booking-81372-default-rtdb.firebaseio.com',
    storageBucket: 'cab-booking-81372.appspot.com',
    iosBundleId: 'com.example.ridersApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9iiR4p_LHPTECKNCSZIgtDqsnMMpToz8',
    appId: '1:726525059893:ios:2964c76e7654343f64227c',
    messagingSenderId: '726525059893',
    projectId: 'cab-booking-81372',
    databaseURL: 'https://cab-booking-81372-default-rtdb.firebaseio.com',
    storageBucket: 'cab-booking-81372.appspot.com',
    iosBundleId: 'com.example.ridersApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2PzC-27eHVcexaNAwAuxuETKBgIIN9vU',
    appId: '1:726525059893:web:4cec04e6326394da64227c',
    messagingSenderId: '726525059893',
    projectId: 'cab-booking-81372',
    authDomain: 'cab-booking-81372.firebaseapp.com',
    databaseURL: 'https://cab-booking-81372-default-rtdb.firebaseio.com',
    storageBucket: 'cab-booking-81372.appspot.com',
  );
}
